# Generated by Django 5.0.2 on 2024-05-19 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dashboard_id')},
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('size_w', models.IntegerField()),
                ('size_h', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100, null=True)),
                ('data', models.CharField(max_length=100, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dashboard', 'widget_id')},
            },
        ),
    ]
