# Generated by Django 5.0.2 on 2024-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=100)),
                ('timestamp_accepted', models.DateTimeField()),
                ('timestamp_requested', models.DateTimeField()),
            ],
        ),
    ]
