# Generated by Django 5.0.2 on 2024-05-19 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_occupation', models.CharField(blank=True, default='Current Occupation Placeholder', max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('socials', models.URLField(blank=True)),
                ('education_bachelor', models.CharField(blank=True, default='Science: Computer Science Engineering, Ghent University, 2010', max_length=100)),
                ('education_master', models.CharField(blank=True, default='Science: Computer Science Engineering, Ghent University, 2020', max_length=100)),
                ('interest_1', models.CharField(blank=True, default='Artificial intelligence', max_length=100)),
                ('interest_2', models.CharField(blank=True, default='Augmented and virtual reality', max_length=100)),
                ('interest_3', models.CharField(blank=True, max_length=100)),
                ('interest_4', models.CharField(blank=True, max_length=100)),
                ('interest_5', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True, default="This is a placeholder for your profile page's about section.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
