"""
Django settings for Collimundo project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
from pathlib import Path

# Config files for tests and application
from .config_application import *
from .config_tests import *
from .config_loging import *
from .config_rating_CP import *
from .config_request_CP import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env_var(env_var, default=None):
    value = os.getenv(env_var)
    if value is not None:
        return value
    if default is not None:
        return default
    raise KeyError(f"Key {env_var} not found")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


SECRET_KEY = str(
    get_env_var(
        "DJANGO_SECRET_KEY",
        "django-insecure-npusz-uqe(73zd%rkxv@m05hjv7&ajx(921xr8(q#-cmogs5op",
    )
)
DEBUG = get_env_var("DJANGO_DEBUG", "") != "False"

ALLOWED_HOSTS = ["127.0.0.1", "www.collimundo.com", "collimundo.com"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "schedule",
    "login",
    "profilepages",
    "anymail",
    "widgets",
    "npm",
    "companies",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Collimundo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "Collimundo/templates"),
            os.path.join(BASE_DIR, "dashboard/templates"),
            os.path.join(BASE_DIR, "widgets/templates"),
            os.path.join(BASE_DIR, "login/templates"),
            os.path.join(BASE_DIR, "profilepages/templates"),
            os.path.join(BASE_DIR, "companies/templates"),
            os.path.join(BASE_DIR, "about/templates"),
            os.path.join(BASE_DIR, "admins/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "utils.context_processors.global_vars",
                "utils.context_processors.generate_search_request_id",
            ],
        },
    },
]

# TEMPLATE_CONTEXT_PROCESSORS = [
#     'django.template.context_processors.request',
# ]

WSGI_APPLICATION = "Collimundo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
try:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": get_env_var("DATABASE_NAME"),
            "USER": get_env_var("DATABASE_USER"),
            "PASSWORD": get_env_var("DATABASE_PASSWORD"),
            "HOST": get_env_var("DATABASE_HOST"),
            "PORT": get_env_var("DATABASE_PORT"),
        }
    }
except KeyError:
    print(
        """

--------- UNSET DATABASE SETTINGS ---------

    Please set the database settings

    file:
        Collimundo\\.dotenv\\.env

    needed content:
        DATABASE_NAME=".."
           DATABASE_USER=".."
        DATABASE_PASSWORD=".."
        DATABASE_HOST=".."
        DATABASE_PORT=".."

-------------------------------------------

    """
    )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Npm packages (gridstack.js -> npm install gridstack --save-prod)
# https://github.com/gridstack/gridstack.js/tree/master/doc
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "npm.finders.NpmFinder",
]
NPM_ROOT_PATH = BASE_DIR
NPM_STATIC_FILES_PREFIX = os.path.join("js", "lib")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Make the use of frames within HTML documents possible
X_FRAME_OPTIONS = "SAMEORIGIN"
CSRF_TRUSTED_ORIGINS = ["https://www.collimundo.com", "https://collimundo.com"]

# Change to a custom user model (highly recommended by Django documentation)
# https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "login.CustomUser"

# Redirect settings for when the user succesfully logs in/out
LOGIN_REDIRECT_URL = "/dashboard"
LOGOUT_REDIRECT_URL = "/dashboard"

# Mail server settings, for forgot password functionality
# https://docs.djangoproject.com/en/5.0/topics/email/#email-backends

# To test it locally (mail will be sent to console):
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Not locally but with mailgun api key:
ANYMAIL = {
    "MAILGUN_API_KEY": "c73e9a9c350c9c799581fd61d31e6aae-86220e6a-7b249380",
    "MAILGUN_API_URL": "https://api.eu.mailgun.net/v3",
    "MAILGUN_SENDER_DOMAIN": "collimundo.com",
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@collimundo.com"
SERVER_EMAIL = "no-reply@collimundo.com"
